// Code generated by SQLBoiler 4.14.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dbmodels

import (
	"bytes"
	"context"
	"reflect"
	"testing"

	"github.com/volatiletech/randomize"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/strmangle"
)

var (
	// Relationships sometimes use the reflection helper queries.Equal/queries.Assign
	// so force a package dependency in case they don't.
	_ = queries.Equal
)

func testAdminUsers(t *testing.T) {
	t.Parallel()

	query := AdminUsers()

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}

func testAdminUsersDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &AdminUser{}
	if err = randomize.Struct(seed, o, adminUserDBTypes, true, adminUserColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize AdminUser struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := AdminUsers().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testAdminUsersQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &AdminUser{}
	if err = randomize.Struct(seed, o, adminUserDBTypes, true, adminUserColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize AdminUser struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := AdminUsers().DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := AdminUsers().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testAdminUsersSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &AdminUser{}
	if err = randomize.Struct(seed, o, adminUserDBTypes, true, adminUserColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize AdminUser struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := AdminUserSlice{o}

	if rowsAff, err := slice.DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := AdminUsers().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testAdminUsersExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &AdminUser{}
	if err = randomize.Struct(seed, o, adminUserDBTypes, true, adminUserColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize AdminUser struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	e, err := AdminUserExists(ctx, tx, o.ID)
	if err != nil {
		t.Errorf("Unable to check if AdminUser exists: %s", err)
	}
	if !e {
		t.Errorf("Expected AdminUserExists to return true, but got false.")
	}
}

func testAdminUsersFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &AdminUser{}
	if err = randomize.Struct(seed, o, adminUserDBTypes, true, adminUserColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize AdminUser struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	adminUserFound, err := FindAdminUser(ctx, tx, o.ID)
	if err != nil {
		t.Error(err)
	}

	if adminUserFound == nil {
		t.Error("want a record, got nil")
	}
}

func testAdminUsersBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &AdminUser{}
	if err = randomize.Struct(seed, o, adminUserDBTypes, true, adminUserColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize AdminUser struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = AdminUsers().Bind(ctx, tx, o); err != nil {
		t.Error(err)
	}
}

func testAdminUsersOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &AdminUser{}
	if err = randomize.Struct(seed, o, adminUserDBTypes, true, adminUserColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize AdminUser struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if x, err := AdminUsers().One(ctx, tx); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testAdminUsersAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	adminUserOne := &AdminUser{}
	adminUserTwo := &AdminUser{}
	if err = randomize.Struct(seed, adminUserOne, adminUserDBTypes, false, adminUserColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize AdminUser struct: %s", err)
	}
	if err = randomize.Struct(seed, adminUserTwo, adminUserDBTypes, false, adminUserColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize AdminUser struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = adminUserOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = adminUserTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := AdminUsers().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testAdminUsersCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	adminUserOne := &AdminUser{}
	adminUserTwo := &AdminUser{}
	if err = randomize.Struct(seed, adminUserOne, adminUserDBTypes, false, adminUserColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize AdminUser struct: %s", err)
	}
	if err = randomize.Struct(seed, adminUserTwo, adminUserDBTypes, false, adminUserColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize AdminUser struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = adminUserOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = adminUserTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := AdminUsers().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}

func adminUserBeforeInsertHook(ctx context.Context, e boil.ContextExecutor, o *AdminUser) error {
	*o = AdminUser{}
	return nil
}

func adminUserAfterInsertHook(ctx context.Context, e boil.ContextExecutor, o *AdminUser) error {
	*o = AdminUser{}
	return nil
}

func adminUserAfterSelectHook(ctx context.Context, e boil.ContextExecutor, o *AdminUser) error {
	*o = AdminUser{}
	return nil
}

func adminUserBeforeUpdateHook(ctx context.Context, e boil.ContextExecutor, o *AdminUser) error {
	*o = AdminUser{}
	return nil
}

func adminUserAfterUpdateHook(ctx context.Context, e boil.ContextExecutor, o *AdminUser) error {
	*o = AdminUser{}
	return nil
}

func adminUserBeforeDeleteHook(ctx context.Context, e boil.ContextExecutor, o *AdminUser) error {
	*o = AdminUser{}
	return nil
}

func adminUserAfterDeleteHook(ctx context.Context, e boil.ContextExecutor, o *AdminUser) error {
	*o = AdminUser{}
	return nil
}

func adminUserBeforeUpsertHook(ctx context.Context, e boil.ContextExecutor, o *AdminUser) error {
	*o = AdminUser{}
	return nil
}

func adminUserAfterUpsertHook(ctx context.Context, e boil.ContextExecutor, o *AdminUser) error {
	*o = AdminUser{}
	return nil
}

func testAdminUsersHooks(t *testing.T) {
	t.Parallel()

	var err error

	ctx := context.Background()
	empty := &AdminUser{}
	o := &AdminUser{}

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, o, adminUserDBTypes, false); err != nil {
		t.Errorf("Unable to randomize AdminUser object: %s", err)
	}

	AddAdminUserHook(boil.BeforeInsertHook, adminUserBeforeInsertHook)
	if err = o.doBeforeInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeInsertHook function to empty object, but got: %#v", o)
	}
	adminUserBeforeInsertHooks = []AdminUserHook{}

	AddAdminUserHook(boil.AfterInsertHook, adminUserAfterInsertHook)
	if err = o.doAfterInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterInsertHook function to empty object, but got: %#v", o)
	}
	adminUserAfterInsertHooks = []AdminUserHook{}

	AddAdminUserHook(boil.AfterSelectHook, adminUserAfterSelectHook)
	if err = o.doAfterSelectHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterSelectHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterSelectHook function to empty object, but got: %#v", o)
	}
	adminUserAfterSelectHooks = []AdminUserHook{}

	AddAdminUserHook(boil.BeforeUpdateHook, adminUserBeforeUpdateHook)
	if err = o.doBeforeUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpdateHook function to empty object, but got: %#v", o)
	}
	adminUserBeforeUpdateHooks = []AdminUserHook{}

	AddAdminUserHook(boil.AfterUpdateHook, adminUserAfterUpdateHook)
	if err = o.doAfterUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpdateHook function to empty object, but got: %#v", o)
	}
	adminUserAfterUpdateHooks = []AdminUserHook{}

	AddAdminUserHook(boil.BeforeDeleteHook, adminUserBeforeDeleteHook)
	if err = o.doBeforeDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeDeleteHook function to empty object, but got: %#v", o)
	}
	adminUserBeforeDeleteHooks = []AdminUserHook{}

	AddAdminUserHook(boil.AfterDeleteHook, adminUserAfterDeleteHook)
	if err = o.doAfterDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterDeleteHook function to empty object, but got: %#v", o)
	}
	adminUserAfterDeleteHooks = []AdminUserHook{}

	AddAdminUserHook(boil.BeforeUpsertHook, adminUserBeforeUpsertHook)
	if err = o.doBeforeUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpsertHook function to empty object, but got: %#v", o)
	}
	adminUserBeforeUpsertHooks = []AdminUserHook{}

	AddAdminUserHook(boil.AfterUpsertHook, adminUserAfterUpsertHook)
	if err = o.doAfterUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpsertHook function to empty object, but got: %#v", o)
	}
	adminUserAfterUpsertHooks = []AdminUserHook{}
}

func testAdminUsersInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &AdminUser{}
	if err = randomize.Struct(seed, o, adminUserDBTypes, true, adminUserColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize AdminUser struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := AdminUsers().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testAdminUsersInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &AdminUser{}
	if err = randomize.Struct(seed, o, adminUserDBTypes, true); err != nil {
		t.Errorf("Unable to randomize AdminUser struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Whitelist(adminUserColumnsWithoutDefault...)); err != nil {
		t.Error(err)
	}

	count, err := AdminUsers().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testAdminUserToOneAbstractUserUsingUser(t *testing.T) {
	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var local AdminUser
	var foreign AbstractUser

	seed := randomize.NewSeed()
	if err := randomize.Struct(seed, &local, adminUserDBTypes, false, adminUserColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize AdminUser struct: %s", err)
	}
	if err := randomize.Struct(seed, &foreign, abstractUserDBTypes, false, abstractUserColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize AbstractUser struct: %s", err)
	}

	if err := foreign.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	local.UserID = foreign.InternalID
	if err := local.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := local.User().One(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}

	if check.InternalID != foreign.InternalID {
		t.Errorf("want: %v, got %v", foreign.InternalID, check.InternalID)
	}

	ranAfterSelectHook := false
	AddAbstractUserHook(boil.AfterSelectHook, func(ctx context.Context, e boil.ContextExecutor, o *AbstractUser) error {
		ranAfterSelectHook = true
		return nil
	})

	slice := AdminUserSlice{&local}
	if err = local.L.LoadUser(ctx, tx, false, (*[]*AdminUser)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if local.R.User == nil {
		t.Error("struct should have been eager loaded")
	}

	local.R.User = nil
	if err = local.L.LoadUser(ctx, tx, true, &local, nil); err != nil {
		t.Fatal(err)
	}
	if local.R.User == nil {
		t.Error("struct should have been eager loaded")
	}

	if !ranAfterSelectHook {
		t.Error("failed to run AfterSelect hook for relationship")
	}
}

func testAdminUserToOneSetOpAbstractUserUsingUser(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a AdminUser
	var b, c AbstractUser

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, adminUserDBTypes, false, strmangle.SetComplement(adminUserPrimaryKeyColumns, adminUserColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &b, abstractUserDBTypes, false, strmangle.SetComplement(abstractUserPrimaryKeyColumns, abstractUserColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, abstractUserDBTypes, false, strmangle.SetComplement(abstractUserPrimaryKeyColumns, abstractUserColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	for i, x := range []*AbstractUser{&b, &c} {
		err = a.SetUser(ctx, tx, i != 0, x)
		if err != nil {
			t.Fatal(err)
		}

		if a.R.User != x {
			t.Error("relationship struct not set to correct value")
		}

		if x.R.UserAdminUsers[0] != &a {
			t.Error("failed to append to foreign relationship struct")
		}
		if a.UserID != x.InternalID {
			t.Error("foreign key was wrong value", a.UserID)
		}

		zero := reflect.Zero(reflect.TypeOf(a.UserID))
		reflect.Indirect(reflect.ValueOf(&a.UserID)).Set(zero)

		if err = a.Reload(ctx, tx); err != nil {
			t.Fatal("failed to reload", err)
		}

		if a.UserID != x.InternalID {
			t.Error("foreign key was wrong value", a.UserID, x.InternalID)
		}
	}
}

func testAdminUsersReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &AdminUser{}
	if err = randomize.Struct(seed, o, adminUserDBTypes, true, adminUserColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize AdminUser struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = o.Reload(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testAdminUsersReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &AdminUser{}
	if err = randomize.Struct(seed, o, adminUserDBTypes, true, adminUserColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize AdminUser struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := AdminUserSlice{o}

	if err = slice.ReloadAll(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testAdminUsersSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &AdminUser{}
	if err = randomize.Struct(seed, o, adminUserDBTypes, true, adminUserColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize AdminUser struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := AdminUsers().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	adminUserDBTypes = map[string]string{`ID`: `character varying`, `InternalID`: `integer`, `UserID`: `integer`, `Admin`: `boolean`}
	_                = bytes.MinRead
)

func testAdminUsersUpdate(t *testing.T) {
	t.Parallel()

	if 0 == len(adminUserPrimaryKeyColumns) {
		t.Skip("Skipping table with no primary key columns")
	}
	if len(adminUserAllColumns) == len(adminUserPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &AdminUser{}
	if err = randomize.Struct(seed, o, adminUserDBTypes, true, adminUserColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize AdminUser struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := AdminUsers().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, adminUserDBTypes, true, adminUserPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize AdminUser struct: %s", err)
	}

	if rowsAff, err := o.Update(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only affect one row but affected", rowsAff)
	}
}

func testAdminUsersSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(adminUserAllColumns) == len(adminUserPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &AdminUser{}
	if err = randomize.Struct(seed, o, adminUserDBTypes, true, adminUserColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize AdminUser struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := AdminUsers().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, adminUserDBTypes, true, adminUserPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize AdminUser struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(adminUserAllColumns, adminUserPrimaryKeyColumns) {
		fields = adminUserAllColumns
	} else {
		fields = strmangle.SetComplement(
			adminUserAllColumns,
			adminUserPrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	typ := reflect.TypeOf(o).Elem()
	n := typ.NumField()

	updateMap := M{}
	for _, col := range fields {
		for i := 0; i < n; i++ {
			f := typ.Field(i)
			if f.Tag.Get("boil") == col {
				updateMap[col] = value.Field(i).Interface()
			}
		}
	}

	slice := AdminUserSlice{o}
	if rowsAff, err := slice.UpdateAll(ctx, tx, updateMap); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("wanted one record updated but got", rowsAff)
	}
}

func testAdminUsersUpsert(t *testing.T) {
	t.Parallel()

	if len(adminUserAllColumns) == len(adminUserPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	o := AdminUser{}
	if err = randomize.Struct(seed, &o, adminUserDBTypes, true); err != nil {
		t.Errorf("Unable to randomize AdminUser struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Upsert(ctx, tx, false, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert AdminUser: %s", err)
	}

	count, err := AdminUsers().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &o, adminUserDBTypes, false, adminUserPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize AdminUser struct: %s", err)
	}

	if err = o.Upsert(ctx, tx, true, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert AdminUser: %s", err)
	}

	count, err = AdminUsers().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
