// Code generated by SQLBoiler 4.14.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dbmodels

var TableNames = struct {
	AbstractUsers    string
	SchemaMigrations string
}{
	AbstractUsers:    "abstract_users",
	SchemaMigrations: "schema_migrations",
}
